site_name: SparkDL
repo_name: 'SparkDL'
repo_url: 'https://github.com/SparkDL/docs'
extra:
    version: latest
    article_nav_top: false
    article_nav_bottom: false
pages:
    - Home: index.md
    - BigDL代码分析:
        - BigDL/数据表示.md
        - BigDL/模型定义.md
        - BigDL/Module.md
        - BigDL/Transformer.md
        - BigDL/inference调用链分析.md
        - BigDL/forward.md
        - BigDL/Tensor运算.md
theme: cinder
