site_name: SparkDL
repo_name: 'Fork on GitHub '
repo_url: 'https://github.com/intel-analytics/BigDL'
extra:
    version: latest
    article_nav_top: false
    article_nav_bottom: false
pages:
    - Home: index.md
    - BigDL代码分析:
        - BigDL/模型定义.md
        - BigDL/Module.md
        - BigDL/Graph.md
theme: windmill
