site_name: SparkDL
extra:
    version: latest
    article_nav_top: false
    article_nav_bottom: false
pages:
    - Home: index.md
    - BigDL代码分析: 
        - BigDL/Module.md
        - BigDL/Graph.md
theme: windmill
